/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Textris.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Textris: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("look_desk", () => this.@look_desk, val => this.@look_desk = val);
			VarDef("inv", () => this.@inv, val => this.@inv = val);
			VarDef("location", () => this.@location, val => this.@location = val);
		}

		public StoryVar @look_desk;
		public StoryVar @inv;
		public StoryVar @location;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Textris()
	{
		this.StartPassage = "Title";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Title

	void passage1_Init()
	{
		this.Passages[@"Title"] = new StoryPassage(@"Title", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("You wake up, floating in the dark. Where are you? When are you? Is this death? You move your arm, and you feel water splash. Oh, sweet. Nah, it’s all good, you’re just floating in a sensory deprivation tank! The hatch is above you. You could probably OPEN it.");
		yield return link("OPEN ", " Garage", null);
		yield break;
	}


	// .............
	// #2: Look_Logic

	void passage2_Init()
	{
		this.Passages[@"Look_Logic"] = new StoryPassage(@"Look_Logic", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return lineBreak();
		yield return text("You search the desk, opening all the drawers. There’s a NOTE with a long string of numbers written on it. There’s a tape player, which you could USE to play the TAPE. Other than that, there’s just a bunch of assorted office supplies. Oh, and there’s a GUN.");
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		Vars.look_desk  = true;
		yield return enchantIntoLink(hookRef("lo"), passage2_Fragment_1);
		yield break;
	}

	IStoryThread passage2_Fragment_0()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage2_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage2_Fragment_0);
		yield break;
	}

	// .............
	// #3:  NOPE2

	void passage3_Init()
	{
		this.Passages[@" NOPE2"] = new StoryPassage(@" NOPE2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #4: Tape_Logic

	void passage4_Init()
	{
		this.Passages[@"Tape_Logic"] = new StoryPassage(@"Tape_Logic", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return lineBreak();
		if(Vars.look_desk == false) {
			yield return text("You need a tape player to play the tape. ");
			using (Group("hook", "ut")) {
				yield return text("USE TAPE");
			}
		}
		else {
			yield return text("You pull the tape player out of the desk drawer and put the audio TAPE inside it. You hit play. A gravelly voice starts talking.");
			yield return lineBreak();
			yield return lineBreak();
			yield return text("Hello agent, this is your commander. We have sent you to Moscow to infiltrate a research facility that, we believe, is developing a machine that can alter people’s minds. You have been outfitted with the cyborg implant Total Environmental Transcription/Reactive Information Synthesis, or T.E.T./R.I.S., to aid in your mission. It will allow you to quickly analyze your surroundings and determine your best courses of action. Good luck.");
			yield return lineBreak();
			yield return lineBreak();
			yield return text("The tape ends. ");
			using (Group("hook", "ut")) {
				yield return text("USE TAPE");
			}
		}
		yield return enchantIntoLink(hookRef("ut"), passage4_Fragment_1);
		yield break;
	}

	IStoryThread passage4_Fragment_0()
	{
		yield return passage("Tape_Logic");
		yield break;
	}

	IStoryThread passage4_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage4_Fragment_0);
		yield break;
	}

	// .............
	// #5: North_Logic

	void passage5_Init()
	{
		this.Passages[@"North_Logic"] = new StoryPassage(@"North_Logic", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return lineBreak();
		if(Vars.inv["NOTE"] == true) {
			yield return abort(goToPassage: "Warehouse");
		}
		else {
			yield return text("The door won’t open. Looks like you need a password for this keypad.");
			using (Group("hook", "no")) {
				yield return text("NORTH");
			}
			yield return text(" ");
			using (Group("hook", "no")) {
				yield return text("OPEN");
			}
			yield return text(" ");
		}
		yield return enchantIntoLink(hookRef("no"), passage5_Fragment_1);
		yield break;
	}

	IStoryThread passage5_Fragment_0()
	{
		yield return passage("North_Logic");
		yield break;
	}

	IStoryThread passage5_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage5_Fragment_0);
		yield break;
	}

	// .............
	// #6: Hack_Logic

	void passage6_Init()
	{
		this.Passages[@"Hack_Logic"] = new StoryPassage(@"Hack_Logic", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return lineBreak();
		yield return text("You try to HACK the keypad next to the door. You don’t get the door open, but you do learn that the password is long, and would be difficult to remember for underpaid guards.");
		using (Group("hook", "ha")) {
			yield return text("HACK");
		}
		yield return enchantIntoLink(hookRef("ha"), passage6_Fragment_1);
		yield break;
	}

	IStoryThread passage6_Fragment_0()
	{
		yield return passage("Hack_Logic");
		yield break;
	}

	IStoryThread passage6_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_0);
		yield break;
	}

	// .............
	// #7:  Garage

	void passage7_Init()
	{
		this.Passages[@" Garage"] = new StoryPassage(@" Garage", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return lineBreak();
		yield return text("You pound on the hatch until it springs open. You haul yourself out of the tank");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You’re in a garage. There is a door to the NORTH, with a keypad next to it. There is a CAMERA in the northwest corner, and another in the northeast. There is a desk with several drawers. You feel something in your pocket. When you check to see what it is, you find an audio TAPE.");
		yield return lineBreak();
		using (Group("hook", "c1")) {
		}
		yield return lineBreak();
		Vars.look_desk  = false;
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text("  ");
		using (Group("hook", "ut")) {
			yield return text("USE TAPE");
		}
		yield return text("  ");
		using (Group("hook", "no")) {
			yield return text("NORTH");
		}
		yield return text("  ");
		using (Group("hook", "ha")) {
			yield return text("HACK");
		}
		yield return text("  ");
		using (Group("hook", "no")) {
			yield return text("OPEN");
		}
		yield return text(" ");
		using (Group("hook", "un")) {
			yield return text("TAKE NOTE");
		}
		yield return text(" ");
		using (Group("hook", "tg")) {
			yield return text("TAKE GUN");
		}
		yield return text(" ");
		using (Group("hook", "ug")) {
			yield return text("USE GUN");
		}
		yield return enchantIntoLink(hookRef("lo"), passage7_Fragment_1);
		yield return enchantIntoLink(hookRef("ut"), passage7_Fragment_3);
		yield return enchantIntoLink(hookRef("no"), passage7_Fragment_5);
		yield return enchantIntoLink(hookRef("ha"), passage7_Fragment_7);
		yield return enchantIntoLink(hookRef("tg"), passage7_Fragment_9);
		yield return enchantIntoLink(hookRef("ug"), passage7_Fragment_11);
		yield return enchantIntoLink(hookRef("un"), passage7_Fragment_13);
		yield break;
	}

	IStoryThread passage7_Fragment_0()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage7_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage7_Fragment_0);
		yield break;
	}

	IStoryThread passage7_Fragment_2()
	{
		yield return passage("Tape_Logic");
		yield break;
	}

	IStoryThread passage7_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage7_Fragment_2);
		yield break;
	}

	IStoryThread passage7_Fragment_4()
	{
		yield return passage("North_Logic");
		yield break;
	}

	IStoryThread passage7_Fragment_5()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage7_Fragment_4);
		yield break;
	}

	IStoryThread passage7_Fragment_6()
	{
		yield return passage("Hack_Logic");
		yield break;
	}

	IStoryThread passage7_Fragment_7()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage7_Fragment_6);
		yield break;
	}

	IStoryThread passage7_Fragment_8()
	{
		yield return passage("Gun_Logic");
		yield break;
	}

	IStoryThread passage7_Fragment_9()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage7_Fragment_8);
		yield break;
	}

	IStoryThread passage7_Fragment_10()
	{
		yield return passage("Gun_Logic2");
		yield break;
	}

	IStoryThread passage7_Fragment_11()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage7_Fragment_10);
		yield break;
	}

	IStoryThread passage7_Fragment_12()
	{
		yield return passage("Note_Logic");
		yield break;
	}

	IStoryThread passage7_Fragment_13()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage7_Fragment_12);
		yield break;
	}

	// .............
	// #8: Gun_Logic

	void passage8_Init()
	{
		this.Passages[@"Gun_Logic"] = new StoryPassage(@"Gun_Logic", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return lineBreak();
		if(Vars.look_desk == true) {
			if(Vars.inv["GUN"] == true) {
				yield return text("You already took the GUN.");
				using (Group("hook", "tg")) {
					yield return text("TAKE GUN");
				}
			}
			else {
				Vars.inv["GUN"]  = true;
				yield return text(" You take the GUN.");
				using (Group("hook", "tg")) {
					yield return text("TAKE GUN");
				}
			}
		}
		else {
			yield return text("What gun?");
			using (Group("hook", "tg")) {
				yield return text("TAKE GUN");
			}
		}
		yield return enchantIntoLink(hookRef("tg"), passage8_Fragment_1);
		yield break;
	}

	IStoryThread passage8_Fragment_0()
	{
		yield return passage("Gun_Logic");
		yield break;
	}

	IStoryThread passage8_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage8_Fragment_0);
		yield break;
	}

	// .............
	// #9: Note_Logic

	void passage9_Init()
	{
		this.Passages[@"Note_Logic"] = new StoryPassage(@"Note_Logic", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return lineBreak();
		if(Vars.look_desk == true) {
			Vars.inv["NOTE"]  = true;
			yield return text(" You read the NOTE. Your cyborg brain easily memorizes the long string of numbers.");
			using (Group("hook", "un")) {
				yield return text("TAKE NOTE");
			}
		}
		else {
			yield return text("What note?");
			using (Group("hook", "un")) {
				yield return text("TAKE NOTE");
			}
		}
		yield return enchantIntoLink(hookRef("un"), passage9_Fragment_1);
		yield break;
	}

	IStoryThread passage9_Fragment_0()
	{
		yield return passage("Note_Logic");
		yield break;
	}

	IStoryThread passage9_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage9_Fragment_0);
		yield break;
	}

	// .............
	// #10: Gun_Logic2

	void passage10_Init()
	{
		this.Passages[@"Gun_Logic2"] = new StoryPassage(@"Gun_Logic2", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return lineBreak();
		if(Vars.look_desk == true) {
			if(Vars.inv["GUN"] == true) {
				yield return text("You shoot the GUN.");
				using (Group("hook", "ug")) {
					yield return text("USE GUN");
				}
			}
			else {
				yield return text("What gun?");
				using (Group("hook", "ug")) {
					yield return text("USE GUN");
				}
			}
			yield return text(" ");
		}
		else {
			yield return text("What gun?");
			using (Group("hook", "ug")) {
				yield return text("USE GUN");
			}
		}
		yield return enchantIntoLink(hookRef("ug"), passage10_Fragment_1);
		yield break;
	}

	IStoryThread passage10_Fragment_0()
	{
		yield return passage("Gun_Logic2");
		yield break;
	}

	IStoryThread passage10_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage10_Fragment_0);
		yield break;
	}

	// .............
	// #11: Init

	void passage11_Init()
	{
		this.Passages[@"Init"] = new StoryPassage(@"Init", new string[]{ "startup", }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		Vars.inv  = macros1.dm("GUN", false, "NOTE", false);
		Vars.location  = macros1.dm("GARAGE", true, "WAREHOUSE", false);
		yield break;
	}


	// .............
	// #12: Warehouse

	void passage12_Init()
	{
		this.Passages[@"Warehouse"] = new StoryPassage(@"Warehouse", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("The door swings open");
		yield break;
	}


}