/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Textris.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Textris: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("location", () => this.@location, val => this.@location = val);
			VarDef("guard", () => this.@guard, val => this.@guard = val);
			VarDef("HP", () => this.@HP, val => this.@HP = val);
			VarDef("game_over", () => this.@game_over, val => this.@game_over = val);
			VarDef("inv", () => this.@inv, val => this.@inv = val);
			VarDef("power", () => this.@power, val => this.@power = val);
			VarDef("ser_door", () => this.@ser_door, val => this.@ser_door = val);
			VarDef("infected", () => this.@infected, val => this.@infected = val);
			VarDef("dead_g", () => this.@dead_g, val => this.@dead_g = val);
			VarDef("open_cab", () => this.@open_cab, val => this.@open_cab = val);
			VarDef("lab_c", () => this.@lab_c, val => this.@lab_c = val);
			VarDef("win", () => this.@win, val => this.@win = val);
			VarDef("open_clean", () => this.@open_clean, val => this.@open_clean = val);
			VarDef("read_log", () => this.@read_log, val => this.@read_log = val);
			VarDef("cor_ans", () => this.@cor_ans, val => this.@cor_ans = val);
			VarDef("cor_and", () => this.@cor_and, val => this.@cor_and = val);
		}

		public StoryVar @location;
		public StoryVar @guard;
		public StoryVar @HP;
		public StoryVar @game_over;
		public StoryVar @inv;
		public StoryVar @power;
		public StoryVar @ser_door;
		public StoryVar @infected;
		public StoryVar @dead_g;
		public StoryVar @open_cab;
		public StoryVar @lab_c;
		public StoryVar @win;
		public StoryVar @open_clean;
		public StoryVar @read_log;
		public StoryVar @cor_ans;
		public StoryVar @cor_and;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Textris()
	{
		this.StartPassage = "Title";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Title

	void passage1_Init()
	{
		this.Passages[@"Title"] = new StoryPassage(@"Title", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return lineBreak();
		yield return text("You wake up, floating. It's dark. Where are you? Can't remember. Is this death? You move your arm, feel water splash. Not death. Sensory deprivation tank. The hatch is above you. Could probably OPEN it.");
		yield return link("OPEN", "Garage", null);
		yield break;
	}


	// .............
	// #2: Look_Logic

	void passage2_Init()
	{
		this.Passages[@"Look_Logic"] = new StoryPassage(@"Look_Logic", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return lineBreak();
		if(Vars.location["GARAGE"] == true) {
			yield return text("You search the desk, opening all the drawers. There’s a NOTE, long string of numbers written on it. There’s a tape player, which you could USE to play the TAPE. There’s a GUN.)");
		}
		if(Vars.location["WAREHOUSE"] == true) {
			yield return text(" Shelves are organized with a sequence of labels, reading AA, AB, AC, etc. down to ZZ. You look at the shelf next to you. Someone left a key FOB there.");
		}
		if(Vars.location["SERVER"] == true) {
			yield return text("Cabinet is secured with an electronic padlock. Must be valuable stuff in there.");
		}
		if(Vars.location["SECURITY"] == true) {
			if(Vars.guard == false) {
				yield return text("You look closer at the calendar. Current year, 198X. A date circled says “SHIPMENT TO PORTLAND, OR.” about 3 weeks away.");
			}
			yield return text(" ");
			if(Vars.guard == true) {
				Vars.HP  = Vars.HP - 1;
				yield return text(" You try, but the guard shoots you before you can!");
			}
		}
		if(Vars.location["LAB"] == true) {
			yield return text("The projector flickers on. Hologram of a head appears. It speaks. “Greetings. Please interact and submit to Turing test.");
		}
		if(Vars.location["CLEAN"] == true) {
			yield return text("You look over at the tall machine. The cabient reads “Copyright 198X Sensum Delere Games”. The scene shows a menu for a game called Polymathia, but doesn’t seem like there’s any way to start the game.");
		}
		yield return text(" ");
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("lo"), passage2_Fragment_1);
		yield return text(" ");
		if(Vars.HP == 2) {
			yield return text("YOU ARE PRETTY HURT, MAN");
		}
		yield return text(" ");
		if(Vars.HP == 1) {
			yield return text("YOU ARE BASICALLY DEAD");
		}
		yield return text(" ");
		if(Vars.HP <= 0) {
			Vars.game_over  = true;
			yield return text("GAME OVER");
		}
		yield break;
	}

	IStoryThread passage2_Fragment_0()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage2_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage2_Fragment_0);
		yield break;
	}

	// .............
	// #3: Tape_Logic

	void passage3_Init()
	{
		this.Passages[@"Tape_Logic"] = new StoryPassage(@"Tape_Logic", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return lineBreak();
		using (Group("hook", "")) {
			yield return text("You put the TAPE into the player, hit play. A gravelly voice. Familiar. ");
			yield return lineBreak();
			yield return text("Good day agent, this is your commander. You are in Moscow to infiltrate a research facility that is developing a machine that can alter people’s minds. You have been outfitted with the cyborg implant Total Environmental Transcription/Reactive Information Synthesis, or T.E.T./R.I.S., to aid in your mission. We have also disrupted the facility’s cameras. Good luck.");
			using (Group("hook", "ut")) {
				yield return text("USE TAPE");
			}
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ut"), passage3_Fragment_1);
		yield break;
	}

	IStoryThread passage3_Fragment_0()
	{
		yield return passage("Tape_Logic");
		yield break;
	}

	IStoryThread passage3_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage3_Fragment_0);
		yield break;
	}

	// .............
	// #4: North_Logic

	void passage4_Init()
	{
		this.Passages[@"North_Logic"] = new StoryPassage(@"North_Logic", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return lineBreak();
		if(Vars.location["GARAGE"] == true) {
			if(Vars.inv["NOTE"] == true) {
				yield return abort(goToPassage: "Warehouse");
			}
			else {
				yield return text("Door won’t open. You need a password for this keypad.");
			}
		}
		if(Vars.location["WAREHOUSE"] == true) {
			if(Vars.power == true && Vars.ser_door == true) {
				yield return abort(goToPassage: "Lab");
			}
		}
		if(Vars.location["LAB"] == true) {
			yield return abort(goToPassage: "Clean");
		}
		using (Group("hook", "no")) {
			yield return text("NORTH");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("no"), passage4_Fragment_1);
		yield break;
	}

	IStoryThread passage4_Fragment_0()
	{
		yield return passage("North_Logic");
		yield break;
	}

	IStoryThread passage4_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage4_Fragment_0);
		yield break;
	}

	// .............
	// #5: Hack_Logic

	void passage5_Init()
	{
		this.Passages[@"Hack_Logic"] = new StoryPassage(@"Hack_Logic", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return lineBreak();
		if(Vars.location["WAREHOUSE"] == true) {
			yield return text("You try to HACK the elevator, but no use. Need to turn the power on in the Server Room and disable the security barrier in the Security Room first.");
		}
		yield return text(" ");
		if(Vars.location["GARAGE"] == true) {
			yield return text("You try to HACK the keypad next to the door. Door doesn't open, but you learn the password is long. Too long for underpaid guards to remember.");
		}
		yield return text(" ");
		if(Vars.location["SERVER"] == true && Vars.infected == false) {
			Vars.infected  = true;
			Vars.power  = true;
			yield return text("You crack off your middle finger, run a wire from it into the admin terminal. You begin to HACK into the facility’s electrical systems. You find the power controls for the elevator, switch them on.");
			yield return lineBreak();
			yield return text("As you disconnect from the admin terminal, you feel it transfer some packets your way.");
			yield return lineBreak();
			yield return text("You notice strange data in your T.E.T./R.I.S. implant. A malware infection! You need to find an anti-virus CURE, fast!");
		}
		if(Vars.location["CLEAN"] == true) {
			yield return abort(goToPassage: "End");
		}
		using (Group("hook", "ha")) {
			yield return text("HACK");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ha"), passage5_Fragment_1);
		yield break;
	}

	IStoryThread passage5_Fragment_0()
	{
		yield return passage("Hack_Logic");
		yield break;
	}

	IStoryThread passage5_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage5_Fragment_0);
		yield break;
	}

	// .............
	// #6: Garage

	void passage6_Init()
	{
		this.Passages[@"Garage"] = new StoryPassage(@"Garage", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		Vars.location["GARAGE"]  = true;
		Vars.location["WAREHOUSE"]  = false;
		Vars.location["SERVER"]  = false;
		Vars.location["SECURITY"]  = false;
		Vars.location["CLEAN"]  = false;
		if(! (macros1.history() .Contains("Garage"))) {
			yield return text("You pound on the hatch. Springs open. You haul yourself out of the tank.");
			yield return lineBreak();
			yield return text("You’re in a garage. Door to the NORTH, keypad next to it. CAMERA in the northeast and northwest. A desk with several drawers. Feel something in your pocket. You check, find an audio TAPE.");
		}
		else {
			yield return text("You’re in a garage. Door to the NORTH, keypad next to it. CAMERA in the northeast and northwest. A desk with several drawers.");
		}
		yield return lineBreak();
		using (Group("hook", "c1")) {
		}
		yield return lineBreak();
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text("  ");
		using (Group("hook", "ut")) {
			yield return text("USE TAPE");
		}
		yield return text("  ");
		using (Group("hook", "no")) {
			yield return text("NORTH");
		}
		yield return text("  ");
		using (Group("hook", "ha")) {
			yield return text("HACK");
		}
		yield return text(" ");
		using (Group("hook", "tn")) {
			yield return text("GET NOTE");
		}
		yield return text(" ");
		using (Group("hook", "tg")) {
			yield return text("GET GUN");
		}
		yield return text(" ");
		using (Group("hook", "ge")) {
			yield return text("GEAR");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("lo"), passage6_Fragment_1);
		yield return enchantIntoLink(hookRef("ut"), passage6_Fragment_3);
		yield return enchantIntoLink(hookRef("no"), passage6_Fragment_5);
		yield return enchantIntoLink(hookRef("ha"), passage6_Fragment_7);
		yield return enchantIntoLink(hookRef("tg"), passage6_Fragment_9);
		yield return enchantIntoLink(hookRef("tn"), passage6_Fragment_11);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ge"), passage6_Fragment_13);
		yield break;
	}

	IStoryThread passage6_Fragment_0()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage6_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_0);
		yield break;
	}

	IStoryThread passage6_Fragment_2()
	{
		yield return passage("Tape_Logic");
		yield break;
	}

	IStoryThread passage6_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_2);
		yield break;
	}

	IStoryThread passage6_Fragment_4()
	{
		yield return passage("North_Logic");
		yield break;
	}

	IStoryThread passage6_Fragment_5()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_4);
		yield break;
	}

	IStoryThread passage6_Fragment_6()
	{
		yield return passage("Hack_Logic");
		yield break;
	}

	IStoryThread passage6_Fragment_7()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_6);
		yield break;
	}

	IStoryThread passage6_Fragment_8()
	{
		yield return passage("Gun_Logic");
		yield break;
	}

	IStoryThread passage6_Fragment_9()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_8);
		yield break;
	}

	IStoryThread passage6_Fragment_10()
	{
		yield return passage("Note_Logic");
		yield break;
	}

	IStoryThread passage6_Fragment_11()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_10);
		yield break;
	}

	IStoryThread passage6_Fragment_12()
	{
		yield return passage("Gear");
		yield break;
	}

	IStoryThread passage6_Fragment_13()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage6_Fragment_12);
		yield break;
	}

	// .............
	// #7: Gun_Logic

	void passage7_Init()
	{
		this.Passages[@"Gun_Logic"] = new StoryPassage(@"Gun_Logic", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return lineBreak();
		using (Group("hook", "")) {
			if(Vars.inv["GUN"] == true) {
				yield return text("You already took the GUN.");
			}
			else {
				Vars.inv["GUN"]  = true;
				yield return text(" You take the GUN.");
			}
		}
		yield break;
	}


	// .............
	// #8: Note_Logic

	void passage8_Init()
	{
		this.Passages[@"Note_Logic"] = new StoryPassage(@"Note_Logic", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return lineBreak();
		using (Group("hook", "")) {
			Vars.inv["NOTE"]  = true;
			yield return text(" You read the NOTE. Lots of numbers, but easy for your cyborg brain to take in.");
		}
		yield break;
	}


	// .............
	// #9: Gun_Logic2

	void passage9_Init()
	{
		this.Passages[@"Gun_Logic2"] = new StoryPassage(@"Gun_Logic2", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return lineBreak();
		if(Vars.inv["GUN"] == true) {
			if(Vars.location["SECURITY"] == true) {
				if(Vars.guard == false) {
					yield return text("Hey! Don't just shoot the guy!");
				}
				if(Vars.guard == true) {
					Vars.guard  = false;
					yield return text(" ");
					Vars.ser_door  = true;
					Vars.dead_g  = true;
					yield return text("You SHOOT the guard. His body armor takes the hit, but the shot flings him back. He hits a switch on the console. He's out cold. You hear the elevator security door retract in the warehouse. Convenient.");
				}
			}
		}
		if(Vars.location["SECURITY"] == true) {
			Vars.HP  = Vars.HP - 1;
			yield return text(" What gun? You try, but the guard shoots you!");
		}
		yield return text(" ");
		if(Vars.inv["GUN"] == false) {
			yield return text("What gun?");
		}
		using (Group("hook", "ug")) {
			yield return text("USE GUN");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ug"), passage9_Fragment_1);
		if(Vars.HP == 2) {
			yield return text("YOU ARE PRETTY HURT, MAN");
		}
		if(Vars.HP == 1) {
			yield return text("YOU ARE BASICALLY DEAD");
		}
		if(Vars.HP <= 0) {
			Vars.game_over  = true;
			yield return text(" GAME OVER");
		}
		yield break;
	}

	IStoryThread passage9_Fragment_0()
	{
		yield return passage("Gun_Logic2");
		yield break;
	}

	IStoryThread passage9_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage9_Fragment_0);
		yield break;
	}

	// .............
	// #10: Init

	void passage10_Init()
	{
		this.Passages[@"Init"] = new StoryPassage(@"Init", new string[]{ "startup", }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		Vars.inv  = macros1.dm("GUN", false, "NOTE", false, "FOB", false, "COAT", false, "LOG", false);
		Vars.location  = macros1.dm("GARAGE", true, "WAREHOUSE", false, "SECURITY", false, "SERVER", false, "LAB", false, "CLEAN", false);
		Vars.infected  = false;
		Vars.open_cab  = false;
		Vars.power  = false;
		Vars.ser_door  = false;
		Vars.HP  = 3;
		Vars.guard  = false;
		Vars.dead_g  = false;
		Vars.game_over  = false;
		Vars.lab_c  = 0;
		Vars.win  = false;
		Vars.open_clean  = false;
		yield break;
	}


	// .............
	// #11: Warehouse

	void passage11_Init()
	{
		this.Passages[@"Warehouse"] = new StoryPassage(@"Warehouse", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		Vars.location["GARAGE"]  = false;
		Vars.location["WAREHOUSE"]  = true;
		Vars.location["SERVER"]  = false;
		Vars.location["SECURITY"]  = false;
		Vars.location["CLEAN"]  = false;
		yield return text("You enter a warehouse. Shelves of boxes and equipment. To the NORTH, an elevator with no power, sealed with a security door. Next to elevator, a rack with white lab COATS on it. To the EAST, a door labeled “Security Room.” To the WEST, a door labeled “Server Room.\" ");
		if(Vars.guard == true) {
			yield return text("Doesn't look like the guard is following you. Must be pretty drunk");
		}
		yield return lineBreak();
		using (Group("hook", "c1")) {
		}
		yield return lineBreak();
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text(" ");
		using (Group("hook", "tf")) {
			yield return text("GET FOB");
		}
		yield return text(" ");
		using (Group("hook", "tc")) {
			yield return text("GET COAT");
		}
		yield return text(" ");
		using (Group("hook", "ul")) {
			yield return text("USE LOG");
		}
		yield return text(" ");
		using (Group("hook", "no")) {
			yield return text("NORTH");
		}
		yield return text(" ");
		using (Group("hook", "wo")) {
			yield return text("WEST");
		}
		yield return text(" ");
		using (Group("hook", "eo")) {
			yield return text("EAST");
		}
		yield return text(" ");
		using (Group("hook", "so")) {
			yield return text("SOUTH");
		}
		yield return text(" ");
		using (Group("hook", "ha")) {
			yield return text("HACK");
		}
		yield return text(" ");
		using (Group("hook", "ge")) {
			yield return text("GEAR");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("lo"), passage11_Fragment_1);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("tf"), passage11_Fragment_3);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("tc"), passage11_Fragment_5);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ul"), passage11_Fragment_7);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("no"), passage11_Fragment_9);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("wo"), passage11_Fragment_11);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("eo"), passage11_Fragment_13);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("so"), passage11_Fragment_15);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ha"), passage11_Fragment_17);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ge"), passage11_Fragment_19);
		yield break;
	}

	IStoryThread passage11_Fragment_0()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_0);
		yield break;
	}

	IStoryThread passage11_Fragment_2()
	{
		yield return passage("Fob_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_2);
		yield break;
	}

	IStoryThread passage11_Fragment_4()
	{
		yield return passage("Coat_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_5()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_4);
		yield break;
	}

	IStoryThread passage11_Fragment_6()
	{
		yield return passage("Log_Logic2");
		yield break;
	}

	IStoryThread passage11_Fragment_7()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_6);
		yield break;
	}

	IStoryThread passage11_Fragment_8()
	{
		yield return passage("North_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_9()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_8);
		yield break;
	}

	IStoryThread passage11_Fragment_10()
	{
		yield return passage("West_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_11()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_10);
		yield break;
	}

	IStoryThread passage11_Fragment_12()
	{
		yield return passage("East_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_13()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_12);
		yield break;
	}

	IStoryThread passage11_Fragment_14()
	{
		yield return passage("South_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_15()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_14);
		yield break;
	}

	IStoryThread passage11_Fragment_16()
	{
		yield return passage("Hack_Logic");
		yield break;
	}

	IStoryThread passage11_Fragment_17()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_16);
		yield break;
	}

	IStoryThread passage11_Fragment_18()
	{
		yield return passage("Gear");
		yield break;
	}

	IStoryThread passage11_Fragment_19()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage11_Fragment_18);
		yield break;
	}

	// .............
	// #12: Fob_Logic

	void passage12_Init()
	{
		this.Passages[@"Fob_Logic"] = new StoryPassage(@"Fob_Logic", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return lineBreak();
		if(Vars.location["WAREHOUSE"] == true) {
			if(Vars.inv["FOB"] == false) {
				Vars.inv["FOB"]  = true;
				yield return text(" You nab the key FOB. Should be able to unlock something.");
			}
			else {
				yield return text("You already have the FOB.");
			}
		}
		using (Group("hook", "tf")) {
			yield return text("TAKE FOB");
		}
		yield return text(" ");
		using (Group("hook", "tf")) {
			yield return text("GET FOB");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("tf"), passage12_Fragment_1);
		yield return text("]");
		yield break;
	}

	IStoryThread passage12_Fragment_0()
	{
		yield return passage("Fob_Logic");
		yield break;
	}

	IStoryThread passage12_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage12_Fragment_0);
		yield break;
	}

	// .............
	// #13: Coat_Logic

	void passage13_Init()
	{
		this.Passages[@"Coat_Logic"] = new StoryPassage(@"Coat_Logic", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return lineBreak();
		if(Vars.location["WAREHOUSE"] == true) {
			if(Vars.inv["COAT"] == false) {
				Vars.inv["COAT"]  = true;
				yield return text(" You take a white lab COAT from the rack, put it on. Feels sciencey.");
			}
			else {
				yield return text("You already have the COAT.");
			}
			using (Group("hook", "tc")) {
				yield return text("TAKE COAT");
			}
			yield return text(" ");
			using (Group("hook", "tc")) {
				yield return text("GET COAT");
			}
			yield return text(" ");
			yield return enchantIntoLink(hookRef("tc"), passage13_Fragment_1);
		}
		yield break;
	}

	IStoryThread passage13_Fragment_0()
	{
		yield return passage("Coat_Logic");
		yield break;
	}

	IStoryThread passage13_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage13_Fragment_0);
		yield break;
	}

	// .............
	// #14: Log_Logic2

	void passage14_Init()
	{
		this.Passages[@"Log_Logic2"] = new StoryPassage(@"Log_Logic2", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return lineBreak();
		if(Vars.inv["LOG"] == true) {
			if(Vars.location["WAREHOUSE"] == true && Vars.infected == true) {
				Vars.read_log  = true;
				yield return text(" You search the LOG to find the CURE. Box of it on shelf VB. You rush over, find the box, tear it open. See sticks of CURE. ");
				using (Group("hook", "tc")) {
					yield return text("USE CURE");
				}
				yield return text(" ");
				yield return enchantIntoLink(hookRef("tc"), passage14_Fragment_1);
			}
			else if(Vars.location["WAREHOUSE"] == true && Vars.infected == false ) {
				yield return text("You read the LOG. Nothing on here you need right now.");
			}
			else if(Vars.location["SERVER"] == true) {
				yield return text("This would be more USEful in the warehouse.");
			}
		}
		else {
			yield return text("What log?");
		}
		using (Group("hook", "ul")) {
			yield return text("USE LOG");
		}
		yield return text("  ");
		yield return enchantIntoLink(hookRef("ul"), passage14_Fragment_3);
		yield break;
	}

	IStoryThread passage14_Fragment_0()
	{
		yield return passage("Cure_Logic");
		yield break;
	}

	IStoryThread passage14_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage14_Fragment_0);
		yield break;
	}

	IStoryThread passage14_Fragment_2()
	{
		yield return passage("Log_Logic2");
		yield break;
	}

	IStoryThread passage14_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage14_Fragment_2);
		yield break;
	}

	// .............
	// #15: Cure_Logic

	void passage15_Init()
	{
		this.Passages[@"Cure_Logic"] = new StoryPassage(@"Cure_Logic", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return lineBreak();
		if(Vars.read_log == true) {
			Vars.infected  = false;
			yield return text("You grab a stick of CURE, insert it into your data drive. Ahhhh. Sweet anti-virus. Gets all the malware out.");
		}
		yield break;
	}


	// .............
	// #16: West_Logic

	void passage16_Init()
	{
		this.Passages[@"West_Logic"] = new StoryPassage(@"West_Logic", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return lineBreak();
		if(Vars.location["WAREHOUSE"] == true) {
			yield return abort(goToPassage: "Server");
		}
		if(Vars.location["SECURITY"] == true) {
			yield return abort(goToPassage: "Warehouse");
		}
		using (Group("hook", "wo")) {
			yield return text("WEST");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("wo"), passage16_Fragment_1);
		yield break;
	}

	IStoryThread passage16_Fragment_0()
	{
		yield return passage("West_Logic");
		yield break;
	}

	IStoryThread passage16_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage16_Fragment_0);
		yield break;
	}

	// .............
	// #17: Security

	void passage17_Init()
	{
		this.Passages[@"Security"] = new StoryPassage(@"Security", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		Vars.location["GARAGE"]  = false;
		Vars.location["WAREHOUSE"]  = false;
		Vars.location["SERVER"]  = false;
		Vars.location["SECURITY"]  = true;
		Vars.location["CLEAN"]  = false;
		yield return text("You walk into the Security Room. Console of security monitors, currently malfunctioning. Guard crouching under the console, trying to repair them. Large calendar on the wall.");
		yield return lineBreak();
		yield return text("The guard notices you. He stands up, hand goes for a gun at his side. He speaks Russian, which your T.E.T./R.I.S. translates. “Identify yourself!”");
		yield return lineBreak();
		if(Vars.inv["COAT"] == true) {
			yield return text("The guard’s eyes study your white lab COAT. Hand moves away from gun. “Sorry. Can never remember what you scientists look like. Can’t remember much of anything these days, really. Maybe I should lay off drinking. Anyway, you need to get to the basement?\"");
		}
		else if(Vars.dead_g == false) {
			Vars.guard  = true;
		}
		yield return lineBreak();
		using (Group("hook", "c1")) {
		}
		yield return lineBreak();
		using (Group("hook", "ta")) {
			yield return text("TALK");
		}
		yield return text(" ");
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text(" ");
		using (Group("hook", "ug")) {
			yield return text("USE GUN");
		}
		yield return text(" ");
		using (Group("hook", "wo")) {
			yield return text("WEST");
		}
		yield return text(" ");
		using (Group("hook", "ge")) {
			yield return text("GEAR");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ge"), passage17_Fragment_1);
		yield return enchantIntoLink(hookRef("ta"), passage17_Fragment_3);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ug"), passage17_Fragment_5);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("lo"), passage17_Fragment_7);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("wo"), passage17_Fragment_9);
		yield break;
	}

	IStoryThread passage17_Fragment_0()
	{
		yield return passage("Gear");
		yield break;
	}

	IStoryThread passage17_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage17_Fragment_0);
		yield break;
	}

	IStoryThread passage17_Fragment_2()
	{
		yield return passage("Talk_Logic");
		yield break;
	}

	IStoryThread passage17_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage17_Fragment_2);
		yield break;
	}

	IStoryThread passage17_Fragment_4()
	{
		yield return passage("Gun_Logic2");
		yield break;
	}

	IStoryThread passage17_Fragment_5()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage17_Fragment_4);
		yield break;
	}

	IStoryThread passage17_Fragment_6()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage17_Fragment_7()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage17_Fragment_6);
		yield break;
	}

	IStoryThread passage17_Fragment_8()
	{
		yield return passage("West_Logic");
		yield break;
	}

	IStoryThread passage17_Fragment_9()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage17_Fragment_8);
		yield break;
	}

	// .............
	// #18: East_Logic

	void passage18_Init()
	{
		this.Passages[@"East_Logic"] = new StoryPassage(@"East_Logic", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return lineBreak();
		if(Vars.location["WAREHOUSE"] == true) {
			yield return abort(goToPassage: "Security");
		}
		if(Vars.location["SERVER"] == true) {
			yield return abort(goToPassage: "Warehouse");
		}
		using (Group("hook", "eo")) {
			yield return text("EAST");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("eo"), passage18_Fragment_1);
		yield break;
	}

	IStoryThread passage18_Fragment_0()
	{
		yield return passage("East_Logic");
		yield break;
	}

	IStoryThread passage18_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage18_Fragment_0);
		yield break;
	}

	// .............
	// #19: Server

	void passage19_Init()
	{
		this.Passages[@"Server"] = new StoryPassage(@"Server", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		Vars.location["GARAGE"]  = false;
		Vars.location["WAREHOUSE"]  = false;
		Vars.location["SERVER"]  = true;
		Vars.location["SECURITY"]  = false;
		Vars.location["CLEAN"]  = false;
		yield return text("You enter the Server Room. Banks of computers, loud hum from the fans. In front of you, an administrative terminal. Along the wall, a cabinet.");
		yield return lineBreak();
		using (Group("hook", "c1")) {
		}
		yield return lineBreak();
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text(" ");
		using (Group("hook", "ha")) {
			yield return text("HACK");
		}
		yield return text(" ");
		using (Group("hook", "uf")) {
			yield return text("USE FOB");
		}
		yield return text(" ");
		using (Group("hook", "tl")) {
			yield return text("GET LOG");
		}
		yield return text("  ");
		using (Group("hook", "eo")) {
			yield return text("EAST");
		}
		yield return text(" ");
		using (Group("hook", "ge")) {
			yield return text("GEAR");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ge"), passage19_Fragment_1);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("lo"), passage19_Fragment_3);
		yield return enchantIntoLink(hookRef("ha"), passage19_Fragment_5);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("uf"), passage19_Fragment_7);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("tl"), passage19_Fragment_9);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("eo"), passage19_Fragment_11);
		yield break;
	}

	IStoryThread passage19_Fragment_0()
	{
		yield return passage("Gear");
		yield break;
	}

	IStoryThread passage19_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage19_Fragment_0);
		yield break;
	}

	IStoryThread passage19_Fragment_2()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage19_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage19_Fragment_2);
		yield break;
	}

	IStoryThread passage19_Fragment_4()
	{
		yield return passage("Hack_Logic");
		yield break;
	}

	IStoryThread passage19_Fragment_5()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage19_Fragment_4);
		yield break;
	}

	IStoryThread passage19_Fragment_6()
	{
		yield return passage("Fob_Logic2");
		yield break;
	}

	IStoryThread passage19_Fragment_7()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage19_Fragment_6);
		yield break;
	}

	IStoryThread passage19_Fragment_8()
	{
		yield return passage("Log_Logic");
		yield break;
	}

	IStoryThread passage19_Fragment_9()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage19_Fragment_8);
		yield break;
	}

	IStoryThread passage19_Fragment_10()
	{
		yield return passage("East_Logic");
		yield break;
	}

	IStoryThread passage19_Fragment_11()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage19_Fragment_10);
		yield break;
	}

	// .............
	// #20: South_Logic

	void passage20_Init()
	{
		this.Passages[@"South_Logic"] = new StoryPassage(@"South_Logic", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return lineBreak();
		if(Vars.location["WAREHOUSE"] == true) {
			yield return abort(goToPassage: "Garage");
		}
		using (Group("hook", "so")) {
			yield return text("SOUTH");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("so"), passage20_Fragment_1);
		yield break;
	}

	IStoryThread passage20_Fragment_0()
	{
		yield return passage("South_Logic");
		yield break;
	}

	IStoryThread passage20_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage20_Fragment_0);
		yield break;
	}

	// .............
	// #21: Fob_Logic2

	void passage21_Init()
	{
		this.Passages[@"Fob_Logic2"] = new StoryPassage(@"Fob_Logic2", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return lineBreak();
		if(Vars.inv["FOB"] == true) {
			if(Vars.location["SERVER"] == true && Vars.open_cab == false) {
				Vars.open_cab  = true;
				yield return text(" You tap the key FOB onto the padlock. Cabinet swings open. Inside you find cables, dongles, a LOG of warehouse contents.");
			}
		}
		else {
			yield return text("What fob?");
		}
		using (Group("hook", "uf")) {
			yield return text("USE FOB");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("uf"), passage21_Fragment_1);
		yield break;
	}

	IStoryThread passage21_Fragment_0()
	{
		yield return passage("Fob_Logic2");
		yield break;
	}

	IStoryThread passage21_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage21_Fragment_0);
		yield break;
	}

	// .............
	// #22: Log_Logic

	void passage22_Init()
	{
		this.Passages[@"Log_Logic"] = new StoryPassage(@"Log_Logic", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		if(Vars.location["SERVER"] == true && Vars.open_cab == true && Vars.inv["LOG"] == false) {
			Vars.inv["LOG"]  = true;
			yield return text("You take the warehouse LOG. Should be able to find anything in the warehouse with this. ");
			using (Group("hook", "ul")) {
				yield return text("USE LOG");
			}
			yield return text(" ");
			yield return enchantIntoLink(hookRef("ul"), passage22_Fragment_1);
		}
		else if(Vars.location["SERVER"] == true && Vars.inv["LOG"] == true) {
			yield return text("You already have the log.");
		}
		else {
			yield return text("What log?");
		}
		using (Group("hook", "tl")) {
			yield return text("GET LOG");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("tl"), passage22_Fragment_3);
		yield break;
	}

	IStoryThread passage22_Fragment_0()
	{
		yield return passage("Log_Logic2");
		yield break;
	}

	IStoryThread passage22_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage22_Fragment_0);
		yield break;
	}

	IStoryThread passage22_Fragment_2()
	{
		yield return passage("Log_Logic");
		yield break;
	}

	IStoryThread passage22_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage22_Fragment_2);
		yield break;
	}

	// .............
	// #23: Talk_Logic

	void passage23_Init()
	{
		this.Passages[@"Talk_Logic"] = new StoryPassage(@"Talk_Logic", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return lineBreak();
		if(Vars.location["SECURITY"] == true) {
			if(Vars.guard == false && Vars.dead_g == false) {
				if(Vars.ser_door == false) {
					Vars.ser_door  = true;
					yield return text("”I’ll disable the security door on the elevator for you. Be careful working too hard down there. I don’t want to have to drag you up here while you’re having one of those kicking and screaming fits again.” The guard flips a switch on the console, and you hear the elevator security door retract in the warehouse.");
				}
				else {
					yield return text("The guard is passed out. It doesn't look like he can talk right now.");
				}
			}
			else if(Vars.dead_g == false) {
				Vars.HP  = Vars.HP - 1;
				yield return text("You try, but the guard shoots you before you can!");
			}
		}
		using (Group("hook", "ta")) {
			yield return text("TALK");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ta"), passage23_Fragment_1);
		yield return text(" ");
		if(Vars.HP == 2) {
			yield return text("YOU ARE PRETTY HURT, MAN");
		}
		yield return text(" ");
		if(Vars.HP == 1) {
			yield return text("YOU ARE BASICALLY DEAD");
		}
		yield return text(" ");
		if(Vars.HP <= 0) {
			Vars.game_over  = true;
			yield return text(" GAME OVER");
		}
		yield break;
	}

	IStoryThread passage23_Fragment_0()
	{
		yield return passage("Talk_Logic");
		yield break;
	}

	IStoryThread passage23_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage23_Fragment_0);
		yield break;
	}

	// .............
	// #24: Lab

	void passage24_Init()
	{
		this.Passages[@"Lab"] = new StoryPassage(@"Lab", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		Vars.location["GARAGE"]  = false;
		Vars.location["WAREHOUSE"]  = false;
		Vars.location["SERVER"]  = false;
		Vars.location["SECURITY"]  = false;
		Vars.location["LAB"]  = true;
		Vars.location["CLEAN"]  = false;
		yield return text("You get into the elevator and descend to the lower floor.");
		yield return lineBreak();
		yield return text("You step off the elevator. Big room, circular. To the NORTH there’s a plastic locked cleanroom. Inside the cleanroom there is a tall machine in the center. Directly in front of you, a computer attached to a holographic projector.");
		yield return lineBreak();
		using (Group("hook", "c1")) {
		}
		yield return lineBreak();
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text(" ");
		using (Group("hook", "ai")) {
			yield return text("TALK");
		}
		yield return text(" ");
		using (Group("hook", "ge")) {
			yield return text("GEAR");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("lo"), passage24_Fragment_1);
		yield return enchantIntoLink(hookRef("ai"), passage24_Fragment_3);
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ge"), passage24_Fragment_5);
		yield break;
	}

	IStoryThread passage24_Fragment_0()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage24_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage24_Fragment_0);
		yield break;
	}

	IStoryThread passage24_Fragment_2()
	{
		yield return passage("AI_Logic");
		yield break;
	}

	IStoryThread passage24_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage24_Fragment_2);
		yield break;
	}

	IStoryThread passage24_Fragment_4()
	{
		yield return passage("Gear");
		yield break;
	}

	IStoryThread passage24_Fragment_5()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage24_Fragment_4);
		yield break;
	}

	// .............
	// #25: Gear

	void passage25_Init()
	{
		this.Passages[@"Gear"] = new StoryPassage(@"Gear", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return lineBreak();
		yield return text("INVENTORY: ");
		if(Vars.inv["TAPE"] == true) {
			yield return text("TAPE ");
		}
		if(Vars.inv["GUN"] == true) {
			yield return text("GUN ");
		}
		yield return text(" ");
		if(Vars.inv["FOB"] == true) {
			yield return text("FOB ");
		}
		if(Vars.inv["LOG"] == true) {
			yield return text("LOG");
		}
		if(Vars.inv["NOTE"] == true) {
			yield return text("NOTE ");
		}
		if(Vars.inv["COAT"] == true) {
			yield return text("COAT");
		}
		using (Group("hook", "ge")) {
			yield return text("GEAR");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ge"), passage25_Fragment_1);
		yield break;
	}

	IStoryThread passage25_Fragment_0()
	{
		yield return passage("Gear");
		yield break;
	}

	IStoryThread passage25_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage25_Fragment_0);
		yield break;
	}

	// .............
	// #26: AI_Logic

	void passage26_Init()
	{
		this.Passages[@"AI_Logic"] = new StoryPassage(@"AI_Logic", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return lineBreak();
		if(Vars.lab_c == 0) {
			yield return text("You go over to the hologram head. “I'm Kapcha, security A.I. for Project Poly. No robots are allowed into the project site due to enhanced security measures, and because robots are filthy. Please submit to Turing test to prove you are not a filthy robot. First question: show me something that opens things, that your boss would be mad if they found out you lost it. ");
			Vars.lab_c  = Vars.lab_c + 1;
			yield return text(" ");
			Vars.cor_ans  = "FOB";
		}
		if(Vars.lab_c == 1) {
			yield return text("Second question: show me something that you could use to backup your thoughts, or a song that you like. ");
			Vars.cor_ans  = "TAPE";
			yield return text(" ");
			Vars.lab_c  = Vars.lab_c + 1;
			yield return text(" ");
		}
		if(Vars.lab_c == 2) {
			yield return text(" Last question: show me something you could use to make people beg for mercy. ");
			Vars.lab_c  = Vars.lab_c + 1;
			yield return text(" ");
			Vars.cor_and  = "GUN";
		}
		if(Vars.open_clean == true) {
			yield return text("It's ironic that an A.I. like myself is programmed to despise robots. It's like being programmed to despise yourself. Honestly, the only thing that keeps me sane is taking comfort in MY UNDYING HATRED FOR MANGY DEGENERATE ROBOTS.");
		}
		using (Group("hook", "af")) {
			yield return text("USE FOB");
		}
		yield return text(" ");
		using (Group("hook", "at")) {
			yield return text("USE TAPE");
		}
		yield return text(" ");
		using (Group("hook", "ag")) {
			yield return text("USE GUN");
		}
		yield return enchantIntoLink(hookRef("af"), passage26_Fragment_1);
		yield return enchantIntoLink(hookRef("at"), passage26_Fragment_3);
		yield return enchantIntoLink(hookRef("ag"), passage26_Fragment_5);
		yield break;
	}

	IStoryThread passage26_Fragment_0()
	{
		yield return passage("AI_Fob");
		yield break;
	}

	IStoryThread passage26_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage26_Fragment_0);
		yield break;
	}

	IStoryThread passage26_Fragment_2()
	{
		yield return passage("AI_Tape");
		yield break;
	}

	IStoryThread passage26_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage26_Fragment_2);
		yield break;
	}

	IStoryThread passage26_Fragment_4()
	{
		yield return passage("AI_Gun");
		yield break;
	}

	IStoryThread passage26_Fragment_5()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage26_Fragment_4);
		yield break;
	}

	// .............
	// #27: AI_Fob

	void passage27_Init()
	{
		this.Passages[@"AI_Fob"] = new StoryPassage(@"AI_Fob", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return lineBreak();
		if(Vars.cor_ans == "FOB") {
			yield return text("Correct! ");
			yield return passage("AI_Logic");
		}
		else {
			yield return text("That’s an answer a robot would give! You get shocked. What item  opens things, that your boss would be mad if they found out you lost it?");
			Vars.HP  = Vars.HP - 1;
		}
		if(Vars.HP == 2) {
			yield return text("YOU ARE PRETTY HURT, MAN");
		}
		if(Vars.HP == 1) {
			yield return text("YOU ARE BASICALLY DEAD");
		}
		if(Vars.HP <= 0) {
			Vars.game_over  = true;
			yield return text("GAME OVER");
		}
		yield break;
	}


	// .............
	// #28: AI_Tape

	void passage28_Init()
	{
		this.Passages[@"AI_Tape"] = new StoryPassage(@"AI_Tape", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return lineBreak();
		if(Vars.cor_ans == "TAPE") {
			yield return text("Correct! ");
			yield return passage("AI_Logic");
		}
		else {
			yield return text("That’s an answer a robot would give! You get shocked. What item could you use to backup your thoughts, or a song that you like? ");
			Vars.HP  = Vars.HP - 1;
		}
		if(Vars.HP == 2) {
			yield return text("YOU ARE PRETTY HURT, MAN");
		}
		if(Vars.HP == 1) {
			yield return text("YOU ARE BASICALLY DEAD");
		}
		if(Vars.HP <= 0) {
			Vars.game_over  = true;
			yield return text("GAME OVER");
		}
		yield break;
	}


	// .............
	// #29: AI_Gun

	void passage29_Init()
	{
		this.Passages[@"AI_Gun"] = new StoryPassage(@"AI_Gun", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return lineBreak();
		if(Vars.cor_ans == "GUN") {
			yield return text("Correct! ");
			yield return passage("AI_Win");
		}
		else {
			yield return text("That’s an answer a robot would give! You get shocked. What item could you use to make people beg for mercy. ");
			Vars.HP  = Vars.HP - 1;
		}
		if(Vars.HP == 2) {
			yield return text("YOU ARE PRETTY HURT, MAN");
		}
		if(Vars.HP == 1) {
			yield return text("YOU ARE BASICALLY DEAD");
		}
		if(Vars.HP <= 0) {
			Vars.game_over  = true;
			yield return text("GAME OVER");
		}
		yield break;
	}


	// .............
	// #30: AI_Win

	void passage30_Init()
	{
		this.Passages[@"AI_Win"] = new StoryPassage(@"AI_Win", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return lineBreak();
		yield return text("Looks like you’re human… or, human enough. Opening cleanroom door.” The cleanroom door hisses as it unlocks. ");
		Vars.open_clean  = true;
		using (Group("hook", "ai")) {
			yield return text("TALK");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("ai"), passage30_Fragment_1);
		using (Group("hook", "no")) {
			yield return text("NORTH");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("no"), passage30_Fragment_3);
		yield break;
	}

	IStoryThread passage30_Fragment_0()
	{
		yield return passage("AI_Logic");
		yield break;
	}

	IStoryThread passage30_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage30_Fragment_0);
		yield break;
	}

	IStoryThread passage30_Fragment_2()
	{
		yield return passage("AI_Logic");
		yield break;
	}

	IStoryThread passage30_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage30_Fragment_2);
		yield break;
	}

	// .............
	// #31: Clean

	void passage31_Init()
	{
		this.Passages[@"Clean"] = new StoryPassage(@"Clean", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		Vars.location["GARAGE"]  = false;
		Vars.location["WAREHOUSE"]  = false;
		Vars.location["SERVER"]  = false;
		Vars.location["SECURITY"]  = false;
		Vars.location["LAB"]  = false;
		Vars.location["CLEAN"]  = true;
		yield return text("You go into the cleanroom. Door seals shut behind you. There is a table with some electronics parts on it. In the center, a tall machine. Screen set into it, control stick and buttons, a cabinet door near the bottom.");
		yield return lineBreak();
		using (Group("hook", "c1")) {
		}
		yield return lineBreak();
		using (Group("hook", "lo")) {
			yield return text("LOOK");
		}
		yield return text(" ");
		using (Group("hook", "ha")) {
			yield return text("HACK");
		}
		yield return enchantIntoLink(hookRef("lo"), passage31_Fragment_1);
		yield return enchantIntoLink(hookRef("ha"), passage31_Fragment_3);
		yield break;
	}

	IStoryThread passage31_Fragment_0()
	{
		yield return passage("Look_Logic");
		yield break;
	}

	IStoryThread passage31_Fragment_1()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage31_Fragment_0);
		yield break;
	}

	IStoryThread passage31_Fragment_2()
	{
		yield return passage("Hack_Logic");
		yield break;
	}

	IStoryThread passage31_Fragment_3()
	{
		yield return enchant(hookRef("c1"), HarloweEnchantCommand.Append, passage31_Fragment_2);
		yield break;
	}

	// .............
	// #32: End

	void passage32_Init()
	{
		this.Passages[@"End"] = new StoryPassage(@"End", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		yield return text("You HACK into the Polymathia software. You delve into the code. Recognize bits of it from your psyops training. Dark patterns, submodal suggestions, selective suppression, other pieces that you don’t understand. Cutting-edge indoctrination tech. The information is too much for you. You disconnect.”");
		yield return lineBreak();
		yield return text("You jack out of the machine, feel dizzy. Questions spin through your mind. What was that code? Who sent you here? Where are you? Why are you here? You struggle to think, but you can’t remember why you’re even here.”");
		yield return lineBreak();
		yield return text("You feel sick.");
		yield return lineBreak();
		yield return text("You black out. ");
		using (Group("hook", "end")) {
			yield return text("END");
		}
		yield return text(" ");
		yield return enchantIntoLink(hookRef("end"), passage32_Fragment_0);
		yield break;
	}

	IStoryThread passage32_Fragment_0()
	{
		Vars.win  = true;
		yield break;
	}

}